create or replace dynamic table DW_CP.PUBLIC.NGR_DAILY_PLAYER_PERFORMANCE(
	AGGREGATED_AT,
	GP_ID,
	PLAYER_ID,
	BRAND_ID,
	SITE_ID,
	GGPASS_ID,
	NICKNAME,
	REGION,
	BET,
	BET_COUNT,
	GGR,
	THEO_WIN,
	SLOT_BET,
	SLOT_GGR,
	SLOT_BET_COUNT,
	SLOT_THEO_WIN,
	CASINO_BET,
	CASINO_GGR,
	CASINO_BET_COUNT,
	CASINO_THEO_WIN,
	LIVE_DEALER_BET,
	LIVE_DEALER_GGR,
	LIVE_DEALER_BET_COUNT,
	LIVE_DEALER_THEO_WIN,
	REDEEMED_AMOUNT,
	REDEEMED_AMOUNT_CB,
	REDEEMED_AMOUNT_CASH,
	REDEEMED_AMOUNT_FREE_BUY_BONUS,
	REDEEMED_AMOUNT_FREE_CHIP,
	REDEEMED_AMOUNT_FREE_SPIN,
	REDEEMED_AMOUNT_MY_CASINO_REWARD_CASH,
	REDEEMED_AMOUNT_3RD_PARTY_PROVIDER_CASH,
	REDEEMED_AMOUNT_TNMT_CB,
	REDEEMED_AMOUNT_CRM_CB,
	REDEEMED_AMOUNT_PROMOTION_CB,
	REDEEMED_AMOUNT_TPM_PROMOTION_CB,
	REDEEMED_AMOUNT_TESTING_CB,
	REDEEMED_AMOUNT_CRM_FREESPIN,
	REDEEMED_AMOUNT_TPM_FREESPIN,
	REDEEMED_AMOUNT_3RD_PARTY_PROVIDER_FREESPIN,
	TNMT_CASH_PRIZE,
	NGR
) target_lag = '1 hour' refresh_mode = AUTO initialize = ON_SCHEDULE warehouse = DT_CP_WH
 as

WITH USER_REGION AS (
    SELECT
        GPID,
        REGION,
        ROW_NUMBER() OVER(PARTITION BY GPID ORDER BY CREATEDAT DESC) as rn
    FROM
        DW_BI.BI_PRODUCTION.TABLE_PLAYERINFO_EXTENDED
),

GAME_RTP AS (
    SELECT
        GAME_CODE,
        GAME_RTP
    FROM (
        SELECT
            GAME_CODE,
            GAME_RTP,
            ROW_NUMBER() OVER (PARTITION BY GAME_CODE ORDER BY UPDATED_AT DESC) AS rn
        FROM
            DW_WAREHOUSE.PUBLIC.CP_STATS_PERIODIC_DAILY
    )
    WHERE rn = 1
),

SESSION_DATA AS (
    SELECT
        C.AGGREGATED_AT,
        C.GP_ID, C.GGPASS_ID, C.BRAND_ID, C.SITE_ID, C.NICKNAME,
        R.REGION, C.GENERAL_GAME_TYPE, C.CATEGORY_ID, C.USER_SESSION_ID,
        C.USER_SESSION_FINISHED_AT,
        TIMESTAMPDIFF(MINUTE, C.USER_SESSION_STARTED_AT, C.USER_SESSION_FINISHED_AT) AS TIME_ON_DEVICE,
        ROUND(C.GGR / C.REQUESTED_EXCHANGE_RATE, 8) AS GGR,
        ROUND(C.BET / C.REQUESTED_EXCHANGE_RATE, 8) * (1 - GR.GAME_RTP) AS THEO_WIN,
        ROUND(C.WIN / C.REQUESTED_EXCHANGE_RATE, 8) AS WIN,
        ROUND(C.BET / C.REQUESTED_EXCHANGE_RATE, 8) AS BET,
        C.BET_COUNT, C.WON_GAME_COUNT
    FROM
        DW_WAREHOUSE.PUBLIC.GP_STATISTICS_GAME_CASINO_PER_SESSION AS C
    LEFT JOIN USER_REGION AS R ON R.GPID = C.GP_ID AND R.rn = 1
    LEFT JOIN GAME_RTP AS GR ON GR.GAME_CODE = C.GAME_TYPE
),

SESSION_AGGREGATES AS (
    -- Aggregate session data per day-player
    SELECT
        S.AGGREGATED_AT, 
        S.GP_ID, 
        S.GGPASS_ID, 
        S.BRAND_ID, 
        S.SITE_ID, 
        S.NICKNAME, 
        S.REGION,
        SUM(S.BET) AS BET,
        SUM(S.BET_COUNT) AS BET_COUNT,
        SUM(S.GGR) AS GGR,
        SUM(S.THEO_WIN) AS THEO_WIN,
        SUM(CASE WHEN S.CATEGORY_ID = 'SLOT' THEN S.BET ELSE 0 END) AS SLOT_BET,
        SUM(CASE WHEN S.CATEGORY_ID = 'SLOT' THEN S.GGR ELSE 0 END) AS SLOT_GGR,
        SUM(CASE WHEN S.CATEGORY_ID = 'SLOT' THEN S.BET_COUNT ELSE 0 END) AS SLOT_BET_COUNT,
        SUM(CASE WHEN S.CATEGORY_ID = 'SLOT' THEN S.THEO_WIN ELSE 0 END) AS SLOT_THEO_WIN,
        SUM(CASE WHEN S.CATEGORY_ID = 'CASINO' THEN S.BET ELSE 0 END) AS CASINO_BET,
        SUM(CASE WHEN S.CATEGORY_ID = 'CASINO' THEN S.GGR ELSE 0 END) AS CASINO_GGR,
        SUM(CASE WHEN S.CATEGORY_ID = 'CASINO' THEN S.BET_COUNT ELSE 0 END) AS CASINO_BET_COUNT,
        SUM(CASE WHEN S.CATEGORY_ID = 'CASINO' THEN S.THEO_WIN ELSE 0 END) AS CASINO_THEO_WIN,
        SUM(CASE WHEN S.CATEGORY_ID = 'LIVE_DEALER' THEN S.BET ELSE 0 END) AS LIVE_DEALER_BET,
        SUM(CASE WHEN S.CATEGORY_ID = 'LIVE_DEALER' THEN S.GGR ELSE 0 END) AS LIVE_DEALER_GGR,
        SUM(CASE WHEN S.CATEGORY_ID = 'LIVE_DEALER' THEN S.BET_COUNT ELSE 0 END) AS LIVE_DEALER_BET_COUNT,
        SUM(CASE WHEN S.CATEGORY_ID = 'LIVE_DEALER' THEN S.THEO_WIN ELSE 0 END) AS LIVE_DEALER_THEO_WIN
    FROM SESSION_DATA AS S
    GROUP BY S.AGGREGATED_AT, S.GP_ID, S.GGPASS_ID, S.BRAND_ID, S.SITE_ID, S.NICKNAME, S.REGION
),

COMBINED_PROMOTIONS AS (
    -- Global Data
    SELECT 
        AGGREGATED_AT, 
        GP_ID, 
        BRAND_ID, 
        SITE_ID, 
        WIN_IN_USD, 
        BONUS_TYPE, 
        ISSUE_TYPE,
        PROMOTION_CODE,
        PROVIDER_CODE
    FROM 
        DW_ORIGIN_GLOBAL.GLOBAL_CP_STATS_SCH_STATS.STATS_TX_PROMOTION
    WHERE 
        REWARD_TYPE != 'CASINO_BONUS' OR REWARD_TYPE IS NULL
        

    UNION ALL

    -- WSOP (Ontario) Data
    SELECT 
        AGGREGATED_AT, 
        GP_ID, 
        BRAND_ID, 
        SITE_ID, 
        WIN_IN_USD, 
        BONUS_TYPE, 
        ISSUE_TYPE,
        PROMOTION_CODE,
        PROVIDER_CODE
    FROM 
         DW_ORIGIN_WSOP.WSOP_CP_STATS_SCH_STATS.STATS_TX_PROMOTION 
    WHERE 
        REWARD_TYPE != 'CASINO_BONUS' OR REWARD_TYPE IS NULL
),

TNMT_PRIZE AS (
    SELECT 
        CAST(CREATED_AT AS DATE) AS CREATED_AT,
        GP_ID,
        SUM(CASE WHEN WALLET_TYPE = 'CASH' THEN AMOUNT ELSE 0 END) AS TNMT_CASH_PRIZE -- ALL CURRENCY IS USD
    FROM DW_ORIGIN_GLOBAL.GLOBAL_GGVEGAS_DB_GGVEGAS.TNMT_PLAYER_PRIZE
    GROUP BY 1,2
    
),

REDEEMED_AMOUNT AS (
    -- Aggregate promotion data per day-player
    SELECT
        AGGREGATED_AT,
        GP_ID,
        BRAND_ID,
        SITE_ID,
        SUM(WIN_IN_USD) AS REDEEMED_AMOUNT, -- WHERE REWARD TYPE = CASH OR NULL(BEFORE MAINTENANCE REWARD TYPE = NULL)
        
        SUM(CASE WHEN BONUS_TYPE = 'Casino Bonus' OR PROMOTION_CODE LIKE '%CASINO_BONUS%' THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_CB,
        SUM(CASE WHEN BONUS_TYPE = 'Cash' OR PROMOTION_CODE LIKE '%CASH%' OR PROMOTION_CODE LIKE '%DROP%' OR PROMOTION_CODE LIKE '%DAILY_WINS%' OR PROMOTION_CODE LIKE '%SLOT_RACE%'
            THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_CASH,
        SUM(CASE WHEN BONUS_TYPE = 'Free Buy Bonus' OR PROMOTION_CODE LIKE '%FREE_BUY%' THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_FREE_BUY_BONUS,
        SUM(CASE WHEN BONUS_TYPE = 'Free Chip' OR PROMOTION_CODE LIKE '%CHIP%'THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_FREE_CHIP,
        SUM(CASE WHEN BONUS_TYPE = 'Free Spin' OR PROMOTION_CODE LIKE '%FREE_SPIN%' THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_FREE_SPIN,  
        
        
        -- CASH
        SUM(CASE WHEN (BONUS_TYPE = 'Cash' OR BONUS_TYPE IS NULL) AND ISSUE_TYPE = 'MY_CASINO_REWARD' THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_MY_CASINO_REWARD_CASH,
        SUM(CASE WHEN (BONUS_TYPE = 'Cash' OR BONUS_TYPE IS NULL) AND (ISSUE_TYPE = 'UNKNOWN' OR STARTSWITH(PROMOTION_CODE, PROVIDER_CODE))   
        THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_3RD_PARTY_PROVIDER_CASH,
        SUM(CASE WHEN (BONUS_TYPE = 'Cash' OR BONUS_TYPE IS NULL) AND ISSUE_TYPE = 'UNKNOWN' OR PROMOTION_CODE LIKE '%TOURNAMENT%'   
        THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_TNMT_CASH,


        -- CASINO BONUS
        SUM(CASE WHEN (BONUS_TYPE = 'Casino Bonus' OR BONUS_TYPE IS NULL) AND PROMOTION_CODE IN('CASINO_BONUS_CRM', 'CASINO_BONUS_MANUAL') and ISSUE_TYPE != 'TPM' THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_CRM_CB,
        SUM(CASE WHEN (BONUS_TYPE = 'Casino Bonus' OR BONUS_TYPE IS NULL) AND PROMOTION_CODE IN('CASINO_BONUS_CRM', 'CASINO_BONUS_MANUAL') and ISSUE_TYPE = 'TPM' THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_TPM_CRM_CB,
        SUM(CASE WHEN BONUS_TYPE = 'Casino Bonus' AND ISSUE_TYPE = 'CASINO_TOURNAMENT' THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_TNMT_CB,  
        SUM(CASE WHEN (BONUS_TYPE = 'Casino Bonus' OR BONUS_TYPE IS NULL) AND PROMOTION_CODE = 'CASINO_BONUS_PROMOTION' AND ISSUE_TYPE != 'CASINO_TOURNAMENT' AND ISSUE_TYPE != 'TPM' AND ISSUE_TYPE != 'MANUAL (General)' THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_PROMOTION_CB,
        SUM(CASE WHEN (BONUS_TYPE = 'Casino Bonus' OR BONUS_TYPE IS NULL) AND PROMOTION_CODE = 'CASINO_BONUS_PROMOTION' AND ISSUE_TYPE = 'TPM' THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_TPM_PROMOTION_CB,
        SUM(CASE WHEN ISSUE_TYPE = 'MANUAL (General)' AND PROMOTION_CODE = 'CASINO_BONUS_PROMOTION' THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_TESTING_CB,        


        --FREESPINS
        SUM(CASE WHEN (BONUS_TYPE = 'Free Spin' OR BONUS_TYPE IS NULL) AND ISSUE_TYPE in ('AUTOMATIC', 'MANUAL')  THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_CRM_FREESPIN, 

        SUM(CASE WHEN BONUS_TYPE = 'Free Spin' AND ISSUE_TYPE = 'TPM' THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_TPM_FREESPIN,
        
        SUM(CASE WHEN BONUS_TYPE = 'Free Spin' AND ISSUE_TYPE = 'UNKNOWN' THEN WIN_IN_USD ELSE 0 END) AS REDEEMED_AMOUNT_3RD_PARTY_PROVIDER_FREESPIN
    FROM 
        COMBINED_PROMOTIONS
    GROUP BY 
        AGGREGATED_AT, GP_ID, BRAND_ID, SITE_ID
),



DAILY_METRICS AS (
    SELECT
        COALESCE(S.AGGREGATED_AT, R.AGGREGATED_AT, P.CREATED_AT) AS AGGREGATED_AT,
        COALESCE(S.GP_ID, R.GP_ID, P.GP_ID) AS GP_ID,
        COALESCE(S.BRAND_ID, R.BRAND_ID) AS BRAND_ID,
        COALESCE(S.SITE_ID, R.SITE_ID) AS SITE_ID,
        S.GGPASS_ID, 
        S.NICKNAME, 
        S.REGION,
        
        -- Session Metrics
        COALESCE(S.BET, 0) AS BET,
        COALESCE(S.BET_COUNT, 0) AS BET_COUNT,
        COALESCE(S.GGR, 0) AS GGR,
        COALESCE(S.THEO_WIN, 0) AS THEO_WIN,
        COALESCE(S.SLOT_BET, 0) AS SLOT_BET,
        COALESCE(S.SLOT_GGR, 0) AS SLOT_GGR,
        COALESCE(S.SLOT_BET_COUNT, 0) AS SLOT_BET_COUNT,
        COALESCE(S.SLOT_THEO_WIN, 0) AS SLOT_THEO_WIN,
        COALESCE(S.CASINO_BET, 0) AS CASINO_BET,
        COALESCE(S.CASINO_GGR, 0) AS CASINO_GGR,
        COALESCE(S.CASINO_BET_COUNT, 0) AS CASINO_BET_COUNT,
        COALESCE(S.CASINO_THEO_WIN, 0) AS CASINO_THEO_WIN,
        COALESCE(S.LIVE_DEALER_BET, 0) AS LIVE_DEALER_BET,
        COALESCE(S.LIVE_DEALER_GGR, 0) AS LIVE_DEALER_GGR,
        COALESCE(S.LIVE_DEALER_BET_COUNT, 0) AS LIVE_DEALER_BET_COUNT,
        COALESCE(S.LIVE_DEALER_THEO_WIN, 0) AS LIVE_DEALER_THEO_WIN,
        
        -- Redemption Metrics
        COALESCE(R.REDEEMED_AMOUNT, 0) AS REDEEMED_AMOUNT,
        COALESCE(R.REDEEMED_AMOUNT_CB, 0) AS REDEEMED_AMOUNT_CB,
        COALESCE(R.REDEEMED_AMOUNT_CASH, 0) AS REDEEMED_AMOUNT_CASH,
        COALESCE(R.REDEEMED_AMOUNT_FREE_BUY_BONUS, 0) AS REDEEMED_AMOUNT_FREE_BUY_BONUS,
        COALESCE(R.REDEEMED_AMOUNT_FREE_CHIP, 0) AS REDEEMED_AMOUNT_FREE_CHIP,
        COALESCE(R.REDEEMED_AMOUNT_FREE_SPIN, 0) AS REDEEMED_AMOUNT_FREE_SPIN,
        
        COALESCE(R.REDEEMED_AMOUNT_MY_CASINO_REWARD_CASH, 0) AS REDEEMED_AMOUNT_MY_CASINO_REWARD_CASH,
        COALESCE(R.REDEEMED_AMOUNT_3RD_PARTY_PROVIDER_CASH, 0) AS REDEEMED_AMOUNT_3RD_PARTY_PROVIDER_CASH,
        COALESCE(R.REDEEMED_AMOUNT_TNMT_CB, 0) AS REDEEMED_AMOUNT_TNMT_CB,
        COALESCE(R.REDEEMED_AMOUNT_CRM_CB, 0) AS REDEEMED_AMOUNT_CRM_CB,
        COALESCE(R.REDEEMED_AMOUNT_PROMOTION_CB, 0) AS REDEEMED_AMOUNT_PROMOTION_CB,
        COALESCE(R.REDEEMED_AMOUNT_TPM_PROMOTION_CB, 0) AS REDEEMED_AMOUNT_TPM_PROMOTION_CB,
        COALESCE(R.REDEEMED_AMOUNT_TESTING_CB, 0) AS REDEEMED_AMOUNT_TESTING_CB,
        COALESCE(R.REDEEMED_AMOUNT_CRM_FREESPIN, 0) AS REDEEMED_AMOUNT_CRM_FREESPIN,
        COALESCE(R.REDEEMED_AMOUNT_TPM_FREESPIN, 0) AS REDEEMED_AMOUNT_TPM_FREESPIN,
        COALESCE(R.REDEEMED_AMOUNT_3RD_PARTY_PROVIDER_FREESPIN, 0) AS REDEEMED_AMOUNT_3RD_PARTY_PROVIDER_FREESPIN,
  

        COALESCE(P.TNMT_CASH_PRIZE, 0) AS TNMT_CASH_PRIZE

    FROM SESSION_AGGREGATES AS S
    FULL OUTER JOIN REDEEMED_AMOUNT AS R
        ON S.AGGREGATED_AT = R.AGGREGATED_AT
        AND S.GP_ID = R.GP_ID
        AND S.BRAND_ID = R.BRAND_ID
        AND S.SITE_ID = R.SITE_ID
    FULL OUTER JOIN TNMT_PRIZE AS P
        ON P.CREATED_AT = COALESCE(S.AGGREGATED_AT, R.AGGREGATED_AT) -- Join to the combined date
        AND P.GP_ID = COALESCE(S.GP_ID, R.GP_ID)

    
),
PLAYER_ID AS (
    SELECT DISTINCT 
    ID AS PLAYER_ID,
    GPID,
    BRANDID
    FROM DW_WAREHOUSE.PUBLIC.GGCORE_PLAYER
)


SELECT
    M.AGGREGATED_AT,
    M.GP_ID,
    P.PLAYER_ID,
    M.BRAND_ID,
    M.SITE_ID,
    M.GGPASS_ID,
    M.NICKNAME,
    M.REGION,
    
    M.BET,
    M.BET_COUNT,
    M.GGR,
    M.THEO_WIN,
    M.SLOT_BET,
    M.SLOT_GGR,
    M.SLOT_BET_COUNT,
    M.SLOT_THEO_WIN,
    M.CASINO_BET,
    M.CASINO_GGR,
    M.CASINO_BET_COUNT,
    M.CASINO_THEO_WIN,
    M.LIVE_DEALER_BET,
    M.LIVE_DEALER_GGR,
    M.LIVE_DEALER_BET_COUNT,
    M.LIVE_DEALER_THEO_WIN,
    
    M.REDEEMED_AMOUNT,
    M.REDEEMED_AMOUNT_CB,
    M.REDEEMED_AMOUNT_CASH,
    M.REDEEMED_AMOUNT_FREE_BUY_BONUS,
    M.REDEEMED_AMOUNT_FREE_CHIP,
    M.REDEEMED_AMOUNT_FREE_SPIN,
    M.REDEEMED_AMOUNT_MY_CASINO_REWARD_CASH,
    M.REDEEMED_AMOUNT_3RD_PARTY_PROVIDER_CASH,
    M.REDEEMED_AMOUNT_TNMT_CB,
    M.REDEEMED_AMOUNT_CRM_CB,
    M.REDEEMED_AMOUNT_PROMOTION_CB,
    M.REDEEMED_AMOUNT_TPM_PROMOTION_CB,
    M.REDEEMED_AMOUNT_TESTING_CB,
    M.REDEEMED_AMOUNT_CRM_FREESPIN,
    M.REDEEMED_AMOUNT_TPM_FREESPIN,
    M.REDEEMED_AMOUNT_3RD_PARTY_PROVIDER_FREESPIN,
    M.TNMT_CASH_PRIZE,

    -- NGR Calculation
    M.GGR - M.REDEEMED_AMOUNT - M.TNMT_CASH_PRIZE AS NGR

FROM DAILY_METRICS AS M
LEFT JOIN PLAYER_ID AS P
    ON P.GPID = M.GP_ID AND P.BRANDID = M.BRAND_ID;